<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Hong Lun</name>
   <tag></tag>
   <elementGuidId>8f7d3eb4-5074-4688-8ff2-705972c2399b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//yt-formatted-string[@id='text'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#channel-title > #container > #text-container > #text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hoàng Luân tooltip Verified @hoangluanblv•462K subscribers Liên hệ hợp tác: - Hotline: 098 842 88 15 - Mail: booking@box.studio Kênh chính thức của Hoàng Luân, bình luận viên esports ...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>4675278e-9bc4-4160-a5ca-f99821470933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d45c4ac-b11b-462c-be95-33f53eed2146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-channel-name</value>
      <webElementGuid>f0d232bc-f3fc-4a5d-9c8a-21543ca516b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>4e8501e4-156b-4541-bb5d-65f6d8984f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hoàng Luân</value>
      <webElementGuid>52f1a08f-8a25-4aa0-96cf-4b0c22afc54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;channel-title&quot;)/div[@id=&quot;container&quot;]/div[@id=&quot;text-container&quot;]/yt-formatted-string[@id=&quot;text&quot;]</value>
      <webElementGuid>71eaa1f4-b1b1-4ecf-8102-d88015d95f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//yt-formatted-string[@id='text'])[14]</value>
      <webElementGuid>58a1162c-06ce-45e6-861a-62f4c63a74a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='text-container']/yt-formatted-string)[6]</value>
      <webElementGuid>7de5656b-fdfb-47ac-aa46-414cd744889e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more'])[1]/following::yt-formatted-string[3]</value>
      <webElementGuid>2af236d8-45eb-41fc-9c06-9e6ce07a23a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::yt-formatted-string[3]</value>
      <webElementGuid>eb20c909-e2be-4020-bc0b-246b6bf9cb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/ytd-channel-name/div/div/yt-formatted-string</value>
      <webElementGuid>5967d15b-3042-4ae5-bc7f-7c5cd39c695c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[@id = 'text' and (text() = 'Hoàng Luân' or . = 'Hoàng Luân')]</value>
      <webElementGuid>5f089251-fdb2-4d8e-981a-214800b7c4d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
